# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import anyscale_client
from anyscale_client.models.ebs_block_device import EbsBlockDevice  # noqa: E501
from anyscale_client.rest import ApiException

class TestEbsBlockDevice(unittest.TestCase):
    """EbsBlockDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EbsBlockDevice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = anyscale_client.models.ebs_block_device.EbsBlockDevice()  # noqa: E501
        if include_optional :
            return EbsBlockDevice(
                delete_on_termination = True, 
                encrypted = True, 
                iops = 56, 
                kms_key_id = '0', 
                outpost_arn = '0', 
                snapshot_id = '0', 
                throughput = 56, 
                volume_size = 56, 
                volume_type = '0'
            )
        else :
            return EbsBlockDevice(
        )

    def testEbsBlockDevice(self):
        """Test EbsBlockDevice"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
