# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import anyscale_client
from anyscale_client.api.default_api import DefaultApi  # noqa: E501
from anyscale_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = anyscale_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apply_service(self):
        """Test case for apply_service

        Apply Service  # noqa: E501
        """
        pass

    def test_archive_cluster(self):
        """Test case for archive_cluster

        Archive Cluster  # noqa: E501
        """
        pass

    def test_cancel_build(self):
        """Test case for cancel_build

        Cancel Build  # noqa: E501
        """
        pass

    def test_cancel_cluster_environment_build(self):
        """Test case for cancel_cluster_environment_build

        Cancel Cluster Environment Build  # noqa: E501
        """
        pass

    def test_create_app_config(self):
        """Test case for create_app_config

        Create App Config  # noqa: E501
        """
        pass

    def test_create_build(self):
        """Test case for create_build

        Create Build  # noqa: E501
        """
        pass

    def test_create_byod_cluster_environment(self):
        """Test case for create_byod_cluster_environment

        Create Byod Cluster Environment  # noqa: E501
        """
        pass

    def test_create_cloud(self):
        """Test case for create_cloud

        Create Cloud  # noqa: E501
        """
        pass

    def test_create_cluster(self):
        """Test case for create_cluster

        Create Cluster  # noqa: E501
        """
        pass

    def test_create_cluster_compute(self):
        """Test case for create_cluster_compute

        Create Cluster Compute  # noqa: E501
        """
        pass

    def test_create_cluster_environment(self):
        """Test case for create_cluster_environment

        Create Cluster Environment  # noqa: E501
        """
        pass

    def test_create_cluster_environment_build(self):
        """Test case for create_cluster_environment_build

        Create Cluster Environment Build  # noqa: E501
        """
        pass

    def test_create_compute_template(self):
        """Test case for create_compute_template

        Create Compute Template  # noqa: E501
        """
        pass

    def test_create_job(self):
        """Test case for create_job

        Create Job  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create Project  # noqa: E501
        """
        pass

    def test_create_service(self):
        """Test case for create_service

        Create Service  # noqa: E501
        """
        pass

    def test_create_session(self):
        """Test case for create_session

        Create Session  # noqa: E501
        """
        pass

    def test_create_session_command(self):
        """Test case for create_session_command

        Create Session Command  # noqa: E501
        """
        pass

    def test_delete_app_configs(self):
        """Test case for delete_app_configs

        Delete App Configs  # noqa: E501
        """
        pass

    def test_delete_build(self):
        """Test case for delete_build

        Delete Build  # noqa: E501
        """
        pass

    def test_delete_cloud(self):
        """Test case for delete_cloud

        Delete Cloud  # noqa: E501
        """
        pass

    def test_delete_cluster(self):
        """Test case for delete_cluster

        Delete Cluster  # noqa: E501
        """
        pass

    def test_delete_cluster_compute(self):
        """Test case for delete_cluster_compute

        Delete Cluster Compute  # noqa: E501
        """
        pass

    def test_delete_cluster_environment(self):
        """Test case for delete_cluster_environment

        Delete Cluster Environment  # noqa: E501
        """
        pass

    def test_delete_cluster_environment_build(self):
        """Test case for delete_cluster_environment_build

        Delete Cluster Environment Build  # noqa: E501
        """
        pass

    def test_delete_compute_template(self):
        """Test case for delete_compute_template

        Delete Compute Template  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete Project  # noqa: E501
        """
        pass

    def test_delete_session(self):
        """Test case for delete_session

        Delete Session  # noqa: E501
        """
        pass

    def test_get_actor(self):
        """Test case for get_actor

        Get Actor  # noqa: E501
        """
        pass

    def test_get_actor_logs(self):
        """Test case for get_actor_logs

        Get Actor Logs  # noqa: E501
        """
        pass

    def test_get_app_config(self):
        """Test case for get_app_config

        Get App Config  # noqa: E501
        """
        pass

    def test_get_build(self):
        """Test case for get_build

        Get Build  # noqa: E501
        """
        pass

    def test_get_build_logs(self):
        """Test case for get_build_logs

        Get Build Logs  # noqa: E501
        """
        pass

    def test_get_cloud(self):
        """Test case for get_cloud

        Get Cloud  # noqa: E501
        """
        pass

    def test_get_cluster(self):
        """Test case for get_cluster

        Get Cluster  # noqa: E501
        """
        pass

    def test_get_cluster_compute(self):
        """Test case for get_cluster_compute

        Get Cluster Compute  # noqa: E501
        """
        pass

    def test_get_cluster_environment(self):
        """Test case for get_cluster_environment

        Get Cluster Environment  # noqa: E501
        """
        pass

    def test_get_cluster_environment_build(self):
        """Test case for get_cluster_environment_build

        Get Cluster Environment Build  # noqa: E501
        """
        pass

    def test_get_cluster_environment_build_logs(self):
        """Test case for get_cluster_environment_build_logs

        Get Cluster Environment Build Logs  # noqa: E501
        """
        pass

    def test_get_cluster_environment_build_operation(self):
        """Test case for get_cluster_environment_build_operation

        Get Cluster Environment Build Operation  # noqa: E501
        """
        pass

    def test_get_cluster_operation(self):
        """Test case for get_cluster_operation

        Get Cluster Operation  # noqa: E501
        """
        pass

    def test_get_compute_template(self):
        """Test case for get_compute_template

        Get Compute Template  # noqa: E501
        """
        pass

    def test_get_default_cloud(self):
        """Test case for get_default_cloud

        Get Default Cloud  # noqa: E501
        """
        pass

    def test_get_default_cluster_compute(self):
        """Test case for get_default_cluster_compute

        Get Default Cluster Compute  # noqa: E501
        """
        pass

    def test_get_default_cluster_environment_build(self):
        """Test case for get_default_cluster_environment_build

        Get Default Cluster Environment Build  # noqa: E501
        """
        pass

    def test_get_default_compute_config(self):
        """Test case for get_default_compute_config

        Get Default Compute Config  # noqa: E501
        """
        pass

    def test_get_default_project(self):
        """Test case for get_default_project

        Get Default Project  # noqa: E501
        """
        pass

    def test_get_job(self):
        """Test case for get_job

        Get Job  # noqa: E501
        """
        pass

    def test_get_job_logs(self):
        """Test case for get_job_logs

        Get Job Logs  # noqa: E501
        """
        pass

    def test_get_namespace(self):
        """Test case for get_namespace

        Get Namespace  # noqa: E501
        """
        pass

    def test_get_organization_temporary_object_storage_credentials(self):
        """Test case for get_organization_temporary_object_storage_credentials

        Get Organization Temporary Object Storage Credentials  # noqa: E501
        """
        pass

    def test_get_production_job(self):
        """Test case for get_production_job

        Get Production Job  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Get Project  # noqa: E501
        """
        pass

    def test_get_runtime_environment(self):
        """Test case for get_runtime_environment

        Get Runtime Environment  # noqa: E501
        """
        pass

    def test_get_service(self):
        """Test case for get_service

        Get Service  # noqa: E501
        """
        pass

    def test_get_session(self):
        """Test case for get_session

        Get Session  # noqa: E501
        """
        pass

    def test_get_session_command(self):
        """Test case for get_session_command

        Get Session Command  # noqa: E501
        """
        pass

    def test_get_session_event_log(self):
        """Test case for get_session_event_log

        Get Session Event Log  # noqa: E501
        """
        pass

    def test_get_session_for_job(self):
        """Test case for get_session_for_job

        Get Session For Job  # noqa: E501
        """
        pass

    def test_get_session_operation(self):
        """Test case for get_session_operation

        Get Session Operation  # noqa: E501
        """
        pass

    def test_kill_session_command(self):
        """Test case for kill_session_command

        Kill Session Command  # noqa: E501
        """
        pass

    def test_list_app_configs(self):
        """Test case for list_app_configs

        List App Configs  # noqa: E501
        """
        pass

    def test_list_builds(self):
        """Test case for list_builds

        List Builds  # noqa: E501
        """
        pass

    def test_list_cluster_environment_builds(self):
        """Test case for list_cluster_environment_builds

        List Cluster Environment Builds  # noqa: E501
        """
        pass

    def test_list_production_jobs(self):
        """Test case for list_production_jobs

        List Production Jobs  # noqa: E501
        """
        pass

    def test_list_projects(self):
        """Test case for list_projects

        List Projects  # noqa: E501
        """
        pass

    def test_list_services(self):
        """Test case for list_services

        List Services  # noqa: E501
        """
        pass

    def test_list_session_commands(self):
        """Test case for list_session_commands

        List Session Commands  # noqa: E501
        """
        pass

    def test_list_sessions(self):
        """Test case for list_sessions

        List Sessions  # noqa: E501
        """
        pass

    def test_partial_update_organization(self):
        """Test case for partial_update_organization

        Partial Update Organization  # noqa: E501
        """
        pass

    def test_search_actors(self):
        """Test case for search_actors

        Search Actors  # noqa: E501
        """
        pass

    def test_search_clouds(self):
        """Test case for search_clouds

        Search Clouds  # noqa: E501
        """
        pass

    def test_search_cluster_computes(self):
        """Test case for search_cluster_computes

        Search Cluster Computes  # noqa: E501
        """
        pass

    def test_search_cluster_environments(self):
        """Test case for search_cluster_environments

        Search Cluster Environments  # noqa: E501
        """
        pass

    def test_search_clusters(self):
        """Test case for search_clusters

        Search Clusters  # noqa: E501
        """
        pass

    def test_search_compute_templates(self):
        """Test case for search_compute_templates

        Search Compute Templates  # noqa: E501
        """
        pass

    def test_search_jobs(self):
        """Test case for search_jobs

        Search Jobs  # noqa: E501
        """
        pass

    def test_search_projects(self):
        """Test case for search_projects

        Search Projects  # noqa: E501
        """
        pass

    def test_search_sessions(self):
        """Test case for search_sessions

        Search Sessions  # noqa: E501
        """
        pass

    def test_start_cluster(self):
        """Test case for start_cluster

        Start Cluster  # noqa: E501
        """
        pass

    def test_start_session(self):
        """Test case for start_session

        Start Session  # noqa: E501
        """
        pass

    def test_terminate_cluster(self):
        """Test case for terminate_cluster

        Terminate Cluster  # noqa: E501
        """
        pass

    def test_terminate_job(self):
        """Test case for terminate_job

        Terminate Job  # noqa: E501
        """
        pass

    def test_terminate_service(self):
        """Test case for terminate_service

        Terminate Service  # noqa: E501
        """
        pass

    def test_terminate_session(self):
        """Test case for terminate_session

        Terminate Session  # noqa: E501
        """
        pass

    def test_update_app_configs(self):
        """Test case for update_app_configs

        Update App Configs  # noqa: E501
        """
        pass

    def test_update_cloud(self):
        """Test case for update_cloud

        Update Cloud  # noqa: E501
        """
        pass

    def test_update_cluster(self):
        """Test case for update_cluster

        Update Cluster  # noqa: E501
        """
        pass

    def test_update_compute_template(self):
        """Test case for update_compute_template

        Update Compute Template  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update Project  # noqa: E501
        """
        pass

    def test_update_session(self):
        """Test case for update_session

        Update Session  # noqa: E501
        """
        pass

    def test_upsert_sso_config(self):
        """Test case for upsert_sso_config

        Upsert Sso Config  # noqa: E501
        """
        pass

    def test_upsert_test_sso_config(self):
        """Test case for upsert_test_sso_config

        Upsert Test Sso Config  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
