# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import anyscale_client
from anyscale_client.models.gcp_node_options import GCPNodeOptions  # noqa: E501
from anyscale_client.rest import ApiException

class TestGCPNodeOptions(unittest.TestCase):
    """GCPNodeOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GCPNodeOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = anyscale_client.models.gcp_node_options.GCPNodeOptions()  # noqa: E501
        if include_optional :
            return GCPNodeOptions(
                service_account = anyscale_client.models.service_account.ServiceAccount(
                    email = '0', 
                    scopes = [
                        '0'
                        ], ), 
                disks = [
                    anyscale_client.models.gcp_node_disk.GCPNodeDisk(
                        boot = True, 
                        auto_delete = True, 
                        type = '0', 
                        initialize_params = anyscale_client.models.initialize_params.initializeParams(), )
                    ], 
                labels = {
                    'key' : '0'
                    }
            )
        else :
            return GCPNodeOptions(
        )

    def testGCPNodeOptions(self):
        """Test GCPNodeOptions"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
