# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import anyscale_client
from anyscale_client.models.create_cluster import CreateCluster  # noqa: E501
from anyscale_client.rest import ApiException

class TestCreateCluster(unittest.TestCase):
    """CreateCluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateCluster
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = anyscale_client.models.create_cluster.CreateCluster()  # noqa: E501
        if include_optional :
            return CreateCluster(
                name = '0', 
                project_id = '0', 
                cluster_environment_build_id = '0', 
                cluster_compute_id = '0', 
                cluster_compute_config = null, 
                idle_timeout_minutes = 56, 
                allow_public_internet_traffic = True, 
                user_service_access = null
            )
        else :
            return CreateCluster(
                name = '0',
                cluster_environment_build_id = '0',
        )

    def testCreateCluster(self):
        """Test CreateCluster"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
