# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import anyscale_client
from anyscale_client.models.update_cluster import UpdateCluster  # noqa: E501
from anyscale_client.rest import ApiException

class TestUpdateCluster(unittest.TestCase):
    """UpdateCluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateCluster
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = anyscale_client.models.update_cluster.UpdateCluster()  # noqa: E501
        if include_optional :
            return UpdateCluster(
                name = '0', 
                idle_timeout_minutes = 56, 
                cluster_environment_build_id = '0', 
                cluster_compute_id = '0'
            )
        else :
            return UpdateCluster(
        )

    def testUpdateCluster(self):
        """Test UpdateCluster"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
