# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import anyscale_client
from anyscale_client.models.project_list_response import ProjectListResponse  # noqa: E501
from anyscale_client.rest import ApiException

class TestProjectListResponse(unittest.TestCase):
    """ProjectListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProjectListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = anyscale_client.models.project_list_response.ProjectListResponse()  # noqa: E501
        if include_optional :
            return ProjectListResponse(
                results = [
                    anyscale_client.models.project.Project(
                        name = '0', 
                        cluster_config = '0', 
                        description = '0', 
                        id = '0', 
                        creator_id = '0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        organization_id = '0', 
                        active_sessions = 56, 
                        last_activity_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_used_cloud_id = '0', 
                        is_default = True, )
                    ], 
                metadata = null
            )
        else :
            return ProjectListResponse(
                results = [
                    anyscale_client.models.project.Project(
                        name = '0', 
                        cluster_config = '0', 
                        description = '0', 
                        id = '0', 
                        creator_id = '0', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        organization_id = '0', 
                        active_sessions = 56, 
                        last_activity_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_used_cloud_id = '0', 
                        is_default = True, )
                    ],
        )

    def testProjectListResponse(self):
        """Test ProjectListResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
