# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import anyscale_client
from anyscale_client.models.clusterenvironmentbuild_response import ClusterenvironmentbuildResponse  # noqa: E501
from anyscale_client.rest import ApiException

class TestClusterenvironmentbuildResponse(unittest.TestCase):
    """ClusterenvironmentbuildResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ClusterenvironmentbuildResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = anyscale_client.models.clusterenvironmentbuild_response.ClusterenvironmentbuildResponse()  # noqa: E501
        if include_optional :
            return ClusterenvironmentbuildResponse(
                result = anyscale_client.models.cluster_environment_build.ClusterEnvironmentBuild(
                    cluster_environment_id = '0', 
                    config_json = null, 
                    id = '0', 
                    revision = 56, 
                    creator_id = '0', 
                    docker_image_name = '0', 
                    error_message = '0', 
                    status = null, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else :
            return ClusterenvironmentbuildResponse(
                result = anyscale_client.models.cluster_environment_build.ClusterEnvironmentBuild(
                    cluster_environment_id = '0', 
                    config_json = null, 
                    id = '0', 
                    revision = 56, 
                    creator_id = '0', 
                    docker_image_name = '0', 
                    error_message = '0', 
                    status = null, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
        )

    def testClusterenvironmentbuildResponse(self):
        """Test ClusterenvironmentbuildResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
