# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import anyscale_client
from anyscale_client.models.update_session import UpdateSession  # noqa: E501
from anyscale_client.rest import ApiException

class TestUpdateSession(unittest.TestCase):
    """UpdateSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UpdateSession
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = anyscale_client.models.update_session.UpdateSession()  # noqa: E501
        if include_optional :
            return UpdateSession(
                cluster_config = '0', 
                idle_timeout = 56
            )
        else :
            return UpdateSession(
        )

    def testUpdateSession(self):
        """Test UpdateSession"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
