# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import anyscale_client
from anyscale_client.models.job_list_response import JobListResponse  # noqa: E501
from anyscale_client.rest import ApiException

class TestJobListResponse(unittest.TestCase):
    """JobListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JobListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = anyscale_client.models.job_list_response.JobListResponse()  # noqa: E501
        if include_optional :
            return JobListResponse(
                results = [
                    anyscale_client.models.job.Job(
                        id = '0', 
                        ray_session_name = '0', 
                        ray_job_id = '0', 
                        name = '0', 
                        status = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ray_job_submission_id = '0', 
                        cluster_id = '0', 
                        namespace_id = '0', 
                        runtime_environment_id = '0', 
                        project_id = '0', 
                        creator_id = '0', )
                    ], 
                metadata = null
            )
        else :
            return JobListResponse(
                results = [
                    anyscale_client.models.job.Job(
                        id = '0', 
                        ray_session_name = '0', 
                        ray_job_id = '0', 
                        name = '0', 
                        status = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ray_job_submission_id = '0', 
                        cluster_id = '0', 
                        namespace_id = '0', 
                        runtime_environment_id = '0', 
                        project_id = '0', 
                        creator_id = '0', )
                    ],
        )

    def testJobListResponse(self):
        """Test JobListResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
