# coding: utf-8

"""
    Anyscale API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from anyscale_client.configuration import Configuration


class StartSessionOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cluster_config': 'str',
        'build_id': 'str',
        'compute_template_id': 'str',
        'allow_public_internet_traffic': 'bool'
    }

    attribute_map = {
        'cluster_config': 'cluster_config',
        'build_id': 'build_id',
        'compute_template_id': 'compute_template_id',
        'allow_public_internet_traffic': 'allow_public_internet_traffic'
    }

    def __init__(self, cluster_config=None, build_id=None, compute_template_id=None, allow_public_internet_traffic=None, local_vars_configuration=None):  # noqa: E501
        """StartSessionOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cluster_config = None
        self._build_id = None
        self._compute_template_id = None
        self._allow_public_internet_traffic = None
        self.discriminator = None

        if cluster_config is not None:
            self.cluster_config = cluster_config
        if build_id is not None:
            self.build_id = build_id
        if compute_template_id is not None:
            self.compute_template_id = compute_template_id
        if allow_public_internet_traffic is not None:
            self.allow_public_internet_traffic = allow_public_internet_traffic

    @property
    def cluster_config(self):
        """Gets the cluster_config of this StartSessionOptions.  # noqa: E501

        New cluster config to apply to the Session.  # noqa: E501

        :return: The cluster_config of this StartSessionOptions.  # noqa: E501
        :rtype: str
        """
        return self._cluster_config

    @cluster_config.setter
    def cluster_config(self, cluster_config):
        """Sets the cluster_config of this StartSessionOptions.

        New cluster config to apply to the Session.  # noqa: E501

        :param cluster_config: The cluster_config of this StartSessionOptions.  # noqa: E501
        :type: str
        """

        self._cluster_config = cluster_config

    @property
    def build_id(self):
        """Gets the build_id of this StartSessionOptions.  # noqa: E501

        Build ID to start the session with.  # noqa: E501

        :return: The build_id of this StartSessionOptions.  # noqa: E501
        :rtype: str
        """
        return self._build_id

    @build_id.setter
    def build_id(self, build_id):
        """Sets the build_id of this StartSessionOptions.

        Build ID to start the session with.  # noqa: E501

        :param build_id: The build_id of this StartSessionOptions.  # noqa: E501
        :type: str
        """

        self._build_id = build_id

    @property
    def compute_template_id(self):
        """Gets the compute_template_id of this StartSessionOptions.  # noqa: E501

        Compute template ID to start the session with.  # noqa: E501

        :return: The compute_template_id of this StartSessionOptions.  # noqa: E501
        :rtype: str
        """
        return self._compute_template_id

    @compute_template_id.setter
    def compute_template_id(self, compute_template_id):
        """Sets the compute_template_id of this StartSessionOptions.

        Compute template ID to start the session with.  # noqa: E501

        :param compute_template_id: The compute_template_id of this StartSessionOptions.  # noqa: E501
        :type: str
        """

        self._compute_template_id = compute_template_id

    @property
    def allow_public_internet_traffic(self):
        """Gets the allow_public_internet_traffic of this StartSessionOptions.  # noqa: E501

        Whether public internet traffic can access Serve endpoints or if an authentication token is required. Will not update current value if not provided.  # noqa: E501

        :return: The allow_public_internet_traffic of this StartSessionOptions.  # noqa: E501
        :rtype: bool
        """
        return self._allow_public_internet_traffic

    @allow_public_internet_traffic.setter
    def allow_public_internet_traffic(self, allow_public_internet_traffic):
        """Sets the allow_public_internet_traffic of this StartSessionOptions.

        Whether public internet traffic can access Serve endpoints or if an authentication token is required. Will not update current value if not provided.  # noqa: E501

        :param allow_public_internet_traffic: The allow_public_internet_traffic of this StartSessionOptions.  # noqa: E501
        :type: bool
        """

        self._allow_public_internet_traffic = allow_public_internet_traffic

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StartSessionOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, StartSessionOptions):
            return True

        return self.to_dict() != other.to_dict()
