# This file is intended to be a file which specifically calls out modules to be published to the Astronomer
# Registry as well as top-level provider metadata. The file should not be packaged and solely lives in the
# repo. The modules listed should pertain to latest, released version of the repo.

# Python package name.
package-name: airflow-provider-anyscale
# The name of the provider to be displayed on the Registry. This is typically the name of the service users
# will interact with when using the provider. Ideally, avoid "Airflow" and "Provider" in the name.
display-name: Anyscale
# URL where users should find the documentation for the provider. This could be a link to the README,
# an external docs site, etc.
docs-url: https://github.com/astronomer/airflow-provider-anyscale/blob/main/README.md

# The next sections should be organized by module type (e.g. operators, hooks, functions, decorators, etc.).
#
# Within each section, the ``module`` value should be the path.to.the.module.specifically. For example, if the
# import path for a function is `from sample_provider.hooks.sample_hook import SampleHook` then the value
# should be "sample_provider.hooks.sample.SampleHook".

hooks:
  - module: anyscale_provider.hooks.anyscale.AnyscaleHook

operators:
  - module: anyscale_provider.operators.anyscale.SubmitAnyscaleJob
  - module: anyscale_provider.operators.anyscale.RolloutAnyscaleService

triggers:
  - module: anyscale_provider.triggers.anyscale.AnyscaleJobTrigger
  - module: anyscale_provider.triggers.anyscale.AnyscaleServiceTrigger