# coding: utf-8

"""
    Managed Ray API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ArchivedLogsInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url_head': 'str',
        'url_get': 'str'
    }

    attribute_map = {
        'url_head': 'url_head',
        'url_get': 'url_get'
    }

    def __init__(self, url_head=None, url_get=None, local_vars_configuration=None):  # noqa: E501
        """ArchivedLogsInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._url_head = None
        self._url_get = None
        self.discriminator = None

        self.url_head = url_head
        self.url_get = url_get

    @property
    def url_head(self):
        """Gets the url_head of this ArchivedLogsInfo.  # noqa: E501

        Used to probe when logs are available on s3.  # noqa: E501

        :return: The url_head of this ArchivedLogsInfo.  # noqa: E501
        :rtype: str
        """
        return self._url_head

    @url_head.setter
    def url_head(self, url_head):
        """Sets the url_head of this ArchivedLogsInfo.

        Used to probe when logs are available on s3.  # noqa: E501

        :param url_head: The url_head of this ArchivedLogsInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and url_head is None:  # noqa: E501
            raise ValueError("Invalid value for `url_head`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                url_head is not None and len(url_head) > 2083):
            raise ValueError("Invalid value for `url_head`, length must be less than or equal to `2083`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                url_head is not None and len(url_head) < 1):
            raise ValueError("Invalid value for `url_head`, length must be greater than or equal to `1`")  # noqa: E501

        self._url_head = url_head

    @property
    def url_get(self):
        """Gets the url_get of this ArchivedLogsInfo.  # noqa: E501

        Download link for logs.  # noqa: E501

        :return: The url_get of this ArchivedLogsInfo.  # noqa: E501
        :rtype: str
        """
        return self._url_get

    @url_get.setter
    def url_get(self, url_get):
        """Sets the url_get of this ArchivedLogsInfo.

        Download link for logs.  # noqa: E501

        :param url_get: The url_get of this ArchivedLogsInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and url_get is None:  # noqa: E501
            raise ValueError("Invalid value for `url_get`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                url_get is not None and len(url_get) > 2083):
            raise ValueError("Invalid value for `url_get`, length must be less than or equal to `2083`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                url_get is not None and len(url_get) < 1):
            raise ValueError("Invalid value for `url_get`, length must be greater than or equal to `1`")  # noqa: E501

        self._url_get = url_get

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArchivedLogsInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ArchivedLogsInfo):
            return True

        return self.to_dict() != other.to_dict()
