# coding: utf-8

"""
    Managed Ray API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class CreateAicaEndpoint(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'cloud_id': 'str',
        'aviary_version': 'str',
        'model_config': 'object'
    }

    attribute_map = {
        'name': 'name',
        'cloud_id': 'cloud_id',
        'aviary_version': 'aviary_version',
        'model_config': 'model_config'
    }

    def __init__(self, name=None, cloud_id=None, aviary_version=None, model_config=None, local_vars_configuration=None):  # noqa: E501
        """CreateAicaEndpoint - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._cloud_id = None
        self._aviary_version = None
        self._model_config = None
        self.discriminator = None

        self.name = name
        self.cloud_id = cloud_id
        self.aviary_version = aviary_version
        self.model_config = model_config

    @property
    def name(self):
        """Gets the name of this CreateAicaEndpoint.  # noqa: E501

        Name of the endpoint to be created.  # noqa: E501

        :return: The name of this CreateAicaEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateAicaEndpoint.

        Name of the endpoint to be created.  # noqa: E501

        :param name: The name of this CreateAicaEndpoint.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def cloud_id(self):
        """Gets the cloud_id of this CreateAicaEndpoint.  # noqa: E501

        The cloud id for the endpoint.  # noqa: E501

        :return: The cloud_id of this CreateAicaEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._cloud_id

    @cloud_id.setter
    def cloud_id(self, cloud_id):
        """Sets the cloud_id of this CreateAicaEndpoint.

        The cloud id for the endpoint.  # noqa: E501

        :param cloud_id: The cloud_id of this CreateAicaEndpoint.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and cloud_id is None:  # noqa: E501
            raise ValueError("Invalid value for `cloud_id`, must not be `None`")  # noqa: E501

        self._cloud_id = cloud_id

    @property
    def aviary_version(self):
        """Gets the aviary_version of this CreateAicaEndpoint.  # noqa: E501

        The version of aviary that this endpoint is running.  # noqa: E501

        :return: The aviary_version of this CreateAicaEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._aviary_version

    @aviary_version.setter
    def aviary_version(self, aviary_version):
        """Sets the aviary_version of this CreateAicaEndpoint.

        The version of aviary that this endpoint is running.  # noqa: E501

        :param aviary_version: The aviary_version of this CreateAicaEndpoint.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and aviary_version is None:  # noqa: E501
            raise ValueError("Invalid value for `aviary_version`, must not be `None`")  # noqa: E501

        self._aviary_version = aviary_version

    @property
    def model_config(self):
        """Gets the model_config of this CreateAicaEndpoint.  # noqa: E501

        The configuration for the endpoints models. Key is the model name.  # noqa: E501

        :return: The model_config of this CreateAicaEndpoint.  # noqa: E501
        :rtype: object
        """
        return self._model_config

    @model_config.setter
    def model_config(self, model_config):
        """Sets the model_config of this CreateAicaEndpoint.

        The configuration for the endpoints models. Key is the model name.  # noqa: E501

        :param model_config: The model_config of this CreateAicaEndpoint.  # noqa: E501
        :type: object
        """
        if self.local_vars_configuration.client_side_validation and model_config is None:  # noqa: E501
            raise ValueError("Invalid value for `model_config`, must not be `None`")  # noqa: E501

        self._model_config = model_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateAicaEndpoint):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateAicaEndpoint):
            return True

        return self.to_dict() != other.to_dict()
