# coding: utf-8

"""
    Managed Ray API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InvoicesQuery(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'status': 'list[InvoiceStatus]',
        'product_type': 'list[ProductType]'
    }

    attribute_map = {
        'status': 'status',
        'product_type': 'product_type'
    }

    def __init__(self, status=[], product_type=[], local_vars_configuration=None):  # noqa: E501
        """InvoicesQuery - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._status = None
        self._product_type = None
        self.discriminator = None

        if status is not None:
            self.status = status
        if product_type is not None:
            self.product_type = product_type

    @property
    def status(self):
        """Gets the status of this InvoicesQuery.  # noqa: E501

        Search invoices with status in this list. If this field is an empty set, no filtering is done.  # noqa: E501

        :return: The status of this InvoicesQuery.  # noqa: E501
        :rtype: list[InvoiceStatus]
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InvoicesQuery.

        Search invoices with status in this list. If this field is an empty set, no filtering is done.  # noqa: E501

        :param status: The status of this InvoicesQuery.  # noqa: E501
        :type: list[InvoiceStatus]
        """

        self._status = status

    @property
    def product_type(self):
        """Gets the product_type of this InvoicesQuery.  # noqa: E501

        Search invoices with product_type in this list. If this field is an empty set, no filtering is done.  # noqa: E501

        :return: The product_type of this InvoicesQuery.  # noqa: E501
        :rtype: list[ProductType]
        """
        return self._product_type

    @product_type.setter
    def product_type(self, product_type):
        """Sets the product_type of this InvoicesQuery.

        Search invoices with product_type in this list. If this field is an empty set, no filtering is done.  # noqa: E501

        :param product_type: The product_type of this InvoicesQuery.  # noqa: E501
        :type: list[ProductType]
        """

        self._product_type = product_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvoicesQuery):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InvoicesQuery):
            return True

        return self.to_dict() != other.to_dict()
