# coding: utf-8

"""
    Managed Ray API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class LogDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'log_files': 'list[LogDetail]',
        'next_page_token': 'str'
    }

    attribute_map = {
        'log_files': 'log_files',
        'next_page_token': 'next_page_token'
    }

    def __init__(self, log_files=None, next_page_token=None, local_vars_configuration=None):  # noqa: E501
        """LogDetails - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._log_files = None
        self._next_page_token = None
        self.discriminator = None

        self.log_files = log_files
        if next_page_token is not None:
            self.next_page_token = next_page_token

    @property
    def log_files(self):
        """Gets the log_files of this LogDetails.  # noqa: E501

        collection of LogDetail.  # noqa: E501

        :return: The log_files of this LogDetails.  # noqa: E501
        :rtype: list[LogDetail]
        """
        return self._log_files

    @log_files.setter
    def log_files(self, log_files):
        """Sets the log_files of this LogDetails.

        collection of LogDetail.  # noqa: E501

        :param log_files: The log_files of this LogDetails.  # noqa: E501
        :type: list[LogDetail]
        """
        if self.local_vars_configuration.client_side_validation and log_files is None:  # noqa: E501
            raise ValueError("Invalid value for `log_files`, must not be `None`")  # noqa: E501

        self._log_files = log_files

    @property
    def next_page_token(self):
        """Gets the next_page_token of this LogDetails.  # noqa: E501

        next page token, default None.  # noqa: E501

        :return: The next_page_token of this LogDetails.  # noqa: E501
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token):
        """Sets the next_page_token of this LogDetails.

        next page token, default None.  # noqa: E501

        :param next_page_token: The next_page_token of this LogDetails.  # noqa: E501
        :type: str
        """

        self._next_page_token = next_page_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LogDetails):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LogDetails):
            return True

        return self.to_dict() != other.to_dict()
