# coding: utf-8

"""
    Managed Ray API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class SessionDescribe(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'applied_snapshots': 'list[AppliedSnapshot]',
        'commands': 'list[SessionCommand]'
    }

    attribute_map = {
        'id': 'id',
        'applied_snapshots': 'applied_snapshots',
        'commands': 'commands'
    }

    def __init__(self, id=None, applied_snapshots=None, commands=None, local_vars_configuration=None):  # noqa: E501
        """SessionDescribe - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._applied_snapshots = None
        self._commands = None
        self.discriminator = None

        self.id = id
        self.applied_snapshots = applied_snapshots
        self.commands = commands

    @property
    def id(self):
        """Gets the id of this SessionDescribe.  # noqa: E501


        :return: The id of this SessionDescribe.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SessionDescribe.


        :param id: The id of this SessionDescribe.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def applied_snapshots(self):
        """Gets the applied_snapshots of this SessionDescribe.  # noqa: E501


        :return: The applied_snapshots of this SessionDescribe.  # noqa: E501
        :rtype: list[AppliedSnapshot]
        """
        return self._applied_snapshots

    @applied_snapshots.setter
    def applied_snapshots(self, applied_snapshots):
        """Sets the applied_snapshots of this SessionDescribe.


        :param applied_snapshots: The applied_snapshots of this SessionDescribe.  # noqa: E501
        :type: list[AppliedSnapshot]
        """
        if self.local_vars_configuration.client_side_validation and applied_snapshots is None:  # noqa: E501
            raise ValueError("Invalid value for `applied_snapshots`, must not be `None`")  # noqa: E501

        self._applied_snapshots = applied_snapshots

    @property
    def commands(self):
        """Gets the commands of this SessionDescribe.  # noqa: E501


        :return: The commands of this SessionDescribe.  # noqa: E501
        :rtype: list[SessionCommand]
        """
        return self._commands

    @commands.setter
    def commands(self, commands):
        """Sets the commands of this SessionDescribe.


        :param commands: The commands of this SessionDescribe.  # noqa: E501
        :type: list[SessionCommand]
        """
        if self.local_vars_configuration.client_side_validation and commands is None:  # noqa: E501
            raise ValueError("Invalid value for `commands`, must not be `None`")  # noqa: E501

        self._commands = commands

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SessionDescribe):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SessionDescribe):
            return True

        return self.to_dict() != other.to_dict()
